#
# Copyright (c) 2022 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-reader-rb
subjects:
- kind: ServiceAccount
  name: resource-reader-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: resource-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-reader-sa
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      initContainers:
      - name: intel-gpu-initcontainer
        image: intel/intel-gpu-initcontainer:0.23.0
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/kubernetes/node-feature-discovery/source.d/
          name: nfd-source-hooks
      containers:
      - name: intel-gpu-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-gpu-plugin:0.23.0
        imagePullPolicy: IfNotPresent
        args:
        - "-shared-dev-num=300"
        - "-resource-manager"
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: devfs
          mountPath: /dev/dri
          readOnly: true
        - name: sysfs
          mountPath: /sys/class/drm
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
        - name: podresources
          mountPath: /var/lib/kubelet/pod-resources
      volumes:
      - name: devfs
        hostPath:
          path: /dev/dri
      - name: sysfs
        hostPath:
          path: /sys/class/drm
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: nfd-source-hooks
        hostPath:
          path: /etc/kubernetes/node-feature-discovery/source.d/
          type: DirectoryOrCreate
      - name: podresources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      serviceAccountName: resource-reader-sa
      nodeSelector:
        kubernetes.io/arch: amd64
