#
# Copyright (c) 2022 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: conductor/v1
kind: Workflow
metadata:
  name: conductor-workflow
  namespace: edgeconductor
spec:
  workflows:
  - name: deinit
    steps:
{{ if eq .Ekconfig.Parameters.Customconfig.Registry.Externalurl "" }}
    - name: docker-remove
      input:
      - name: containers-harbor
        schema: containers
    - name: docker-run
      input:
      - name: containers-harbor-cleanup
        schema: containers
    - name: docker-remove
      input:
      - name: containers-harbor-cleanup
        schema: containers
{{ end }}
