#
# Copyright (c) 2022 Intel Corporation. 
#
# SPDX-License-Identifier: Apache-2.0
#
#
controller:
  image:
    digest: ""
  config:
    ssl-ecdh-curve: secp384r1:secp521r1
    ssl-protocols: TLSv1.3
  extraArgs:
    enable-ssl-passthrough: ""
  ingressClassResource:
    default: true
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        8080: 32808
  admissionWebhooks:
    patch:
      image:
        digest: ""
