#
# Copyright (c) 2022 Intel Corporation. 
#
# SPDX-License-Identifier: Apache-2.0
#
#
nodes:
{{- block "nodelist" .}}{{range .Ekconfig.Parameters.Nodes}}
  - address: {{ .IP }}
{{- block "user" .}}{{if .User}}
    user: {{ .User }}
{{else}}
    user: ubuntu
{{- end -}}{{- end}}
{{- block "sshkeypath" .}}{{if .SSHKeyPath}}
    ssh_key_path: {{.SSHKeyPath}}
{{else}}
    ssh_key_path: ~/.ssh/id_rsa
{{- end -}}{{- end}}
    role:
{{- block "rolelist" .}}{{range .Role}}
      - {{.}}
{{- end -}}{{- end}}
{{- end -}}{{- end}}

ssh_key_path: ~/.ssh/id_rsa
private_registries:
    - url: {{ .Ekconfig.Parameters.GlobalSettings.ProviderIP }}:{{ .Ekconfig.Parameters.GlobalSettings.RegistryPort }}/docker.io
      user: {{ .Ekconfig.Parameters.Customconfig.Registry.User }}
      password: {{ .Ekconfig.Parameters.Customconfig.Registry.Password }}
      is_default: true
system_images:
{{- range .Extensions -}}
{{- if eq .Name "cpu-manager" -}}
{{- range .Extension.Extension -}}
{{- if eq .Name "cpu-manager" -}}
{{- range .Config -}}
{{- if eq .Name "rke-kube-image"}}
  kubernetes: {{ .Value }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}
services:
  kubelet:
    extra_args:
{{- range .Extensions -}}
{{- if eq .Name "cpu-manager" -}}
{{- range .Extension.Extension -}}
{{- if eq .Name "node-config" -}}
{{- range .Config -}}
{{- if eq .Name "reserved-cpus"}}
      {{ .Name }}: {{ .Value }}
{{- end -}}
{{- if eq .Name "feature-gates"}}
      {{ .Name }}: {{ .Value }}
{{- end -}}
{{- if eq .Name "cpu-manager-policy"}}
      {{ .Name }}: {{ .Value }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}
ingress:
{{- range .Extensions -}}
{{- if eq .Name "ingress" -}}
{{- range .Extension.Extension -}}
{{- if eq .Name "rke-ingress" -}}
{{- range .Config -}}
{{- if eq .Name "provider"}}
  provider: {{ .Value }}
{{- end -}}
{{- if eq .Name "default-backend"}}
  default_backend: {{ .Value }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}

