#
# Copyright (c) 2022 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#
definitions:
  serviceconfig:
    properties:
      Components:
        type: array
        items:
          $ref: 'component.yml#/definitions/component'
