#
# Copyright (c) 2022 Intel Corporation. 
#
# SPDX-License-Identifier: Apache-2.0
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cluster
  labels:
    app: hello-cluster-example
spec:
  selector:
    matchLabels:
      app: hello-cluster-example
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-cluster-example
    spec:
      containers:
        - name: hello-cluster
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: hello-cluster
  labels:
    app: hello-cluster-example
spec:
  type: NodePort
  selector:
    app: hello-cluster-example
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
