#
# Copyright (c) 2022 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#
cluster_providers:
- name: kind
  version: "v0.12.0"
  images:
  - name: img_node
    repo_tag: "kindest/node:v1.23.4"
  - name: img_haproxy
    repo_tag: "docker.io/kindest/base:v20220505-5e587316"
  binaries:
  - name: kindtool
    url: "https://kind.sigs.k8s.io/dl/v0.12.0/kind-linux-amd64"
    sha256: "b80624c14c807490c0944d21fdc9c3455d6cc904fad486fe236f2187ecaa5789"

- name: rke
  version: "1.3.11"
  binaries:
  - name: rketool
    url: "https://github.com/rancher/rke/releases/download/v1.3.11/rke_linux-amd64"
    sha256: "4583c447a19f1f0ef7d03fd5c49025551f75a86ab5a4a86ef2e617a48a1b3b7e"

clusterapi:
  runtime: "containerd"
  configs:
  - name: "byoh"
    bin_url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/clusterctl-linux-amd64"
    providers:
    - provider_type: "CoreProvider"
      name: "cluster-api"
      url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/core-components.yaml"
      parameters:
        provider_label: "cluster-api"
        version: "v1.1.3"
        metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/metadata.yaml"
    - provider_type: "BootstrapProvider"
      name: "kubeadm"
      url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/bootstrap-components.yaml"
      parameters:
        provider_label: "bootstrap-kubeadm"
        version: "v1.1.3"
        metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/metadata.yaml"
    - provider_type: "ControlPlaneProvider"
      name: "kubeadm"
      url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/control-plane-components.yaml"
      parameters:
        provider_label: "control-plane-kubeadm"
        version: "v1.1.3"
        metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/metadata.yaml"
    - provider_type: "InfrastructureProvider"
      name: "byoh"
      url: "https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/v0.2.0/infrastructure-components.yaml"
      parameters:
        provider_label: "infrastructure-byoh"
        version: "v0.2.0"
        metadata: file://{{ .Workspace }}/config/cluster-provider/capi/byoh/metadata.yaml
    images:
    - "ghcr.io/kube-vip/kube-vip:v0.3.5"
    - "k8s.gcr.io/coredns/coredns:v1.8.6"
    - "k8s.gcr.io/etcd:3.5.1-0"
    - "k8s.gcr.io/kube-apiserver:v1.23.4"
    - "k8s.gcr.io/kube-controller-manager:v1.23.4"
    - "k8s.gcr.io/kube-proxy:v1.23.4"
    - "k8s.gcr.io/kube-scheduler:v1.23.4"
    - "k8s.gcr.io/pause:3.5"
    - "k8s.gcr.io/pause:3.6"
    - "projects.registry.vmware.com/cluster_api_provider_bringyourownhost/cluster-api-byoh-controller:v0.2.0"
    - "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
    - "k8s.gcr.io/cluster-api/cluster-api-controller:v1.1.3"
    - "k8s.gcr.io/cluster-api/kubeadm-bootstrap-controller:v1.1.3"
    - "k8s.gcr.io/cluster-api/kubeadm-control-plane-controller:v1.1.3"
    - "quay.io/jetstack/cert-manager-cainjector:v1.8.0"
    - "quay.io/jetstack/cert-manager-controller:v1.8.0"
    - "quay.io/jetstack/cert-manager-webhook:v1.8.0"
    runtime_bins:
    - name: "crio"
      version: "v1.23.2"
      url: "https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.c0b2474b80fd0844b883729bda88961bed7b472b.tar.gz"
    - name: "containerd"
      version: "1.5.9"
      url: "https://github.com/containerd/containerd/releases/download/v1.5.9/cri-containerd-cni-1.5.9-linux-amd64.tar.gz"
  - name: "metal3"
    bin_url:  "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/clusterctl-linux-amd64"
    providers:
    - provider_type: "CoreProvider"
      name: "cluster-api"
      url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/core-components.yaml"
      parameters:
        provider_label: "cluster-api"
        version: "v1.1.3"
        metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/metadata.yaml"
    - provider_type: "BootstrapProvider"
      name: "kubeadm"
      url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/bootstrap-components.yaml"
      parameters:
        provider_label: "bootstrap-kubeadm"
        version: "v1.1.3"
        metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/metadata.yaml"
    - provider_type: "ControlPlaneProvider"
      name: "kubeadm"
      url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/control-plane-components.yaml"
      parameters:
        provider_label: "control-plane-kubeadm"
        version: "v1.1.3"
        metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/metadata.yaml"
    - provider_type: "InfrastructureProvider"
      name: "metal3"
      url: "https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.1.1/infrastructure-components.yaml"
      parameters:
        provider_label: "infrastructure-metal3"
        version: "v1.1.1"
        metadata: "https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.1.1/metadata.yaml"
    images:
    - "ghcr.io/kube-vip/kube-vip:v0.3.5"
    - "k8s.gcr.io/coredns/coredns:v1.8.6"
    - "k8s.gcr.io/etcd:3.5.1-0"
    - "k8s.gcr.io/kube-apiserver:v1.23.4"
    - "k8s.gcr.io/kube-controller-manager:v1.23.4"
    - "k8s.gcr.io/kube-proxy:v1.23.4"
    - "k8s.gcr.io/kube-scheduler:v1.23.4"
    - "k8s.gcr.io/pause:3.5"
    - "k8s.gcr.io/pause:3.6"
    - "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
    - "k8s.gcr.io/cluster-api/cluster-api-controller:v1.1.3"
    - "k8s.gcr.io/cluster-api/kubeadm-bootstrap-controller:v1.1.3"
    - "k8s.gcr.io/cluster-api/kubeadm-control-plane-controller:v1.1.3"
    - "quay.io/jetstack/cert-manager-cainjector:v1.8.0"
    - "quay.io/jetstack/cert-manager-controller:v1.8.0"
    - "quay.io/jetstack/cert-manager-webhook:v1.8.0"
    - "quay.io/metal3-io/baremetal-operator:capm3-v1.1.1"
    - "quay.io/metal3-io/cluster-api-provider-metal3:v1.1.1"
    - "quay.io/metal3-io/ip-address-manager:v1.1.2"
    - "docker.io/kindest/kindnetd:v20211122-a2c10462"
    - "docker.io/rancher/local-path-provisioner:v0.0.14"
    runtime_bins:
    - name: "crio"
      version: "v1.23.2"
      url: "https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.v1.23.2.tar.gz"
    - name: "containerd"
      version: "1.5.11"
      url: "https://github.com/containerd/containerd/releases/download/v1.5.11/cri-containerd-cni-1.5.11-linux-amd64.tar.gz"
  cert-manager:
    version: "v1.8.0"
    url: "https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.yaml"
  byoh-config:
    host_agent_bin_url: "https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/v0.2.0/byoh-hostagent-linux-amd64"
    download_bin_url: "https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v0.24.0/imgpkg-linux-amd64"
    bundle_registry: "projects.registry.vmware.com/cluster_api_provider_bringyourownhost"
    bundle_image: "byoh-bundle-ubuntu_20.04.1_x86-64_k8s:v1.23.4"
    crio: "https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.c0b2474b80fd0844b883729bda88961bed7b472b.tar.gz"
    