#
# Copyright (c) 2022 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#
Components:
  - name: antrea
    url: https://github.com/antrea-io/antrea/releases/download/v1.5.0/antrea.yml
    type: yaml
    supported-clusters:
    - none

  - name: calico
    url: file://{{ .Workspace }}/services/calico/calico.yaml
    type: yaml
    images:
      - docker.io/calico/cni:v3.23.1
      - docker.io/calico/kube-controllers:v3.23.1
      - docker.io/calico/node:v3.23.1
    supported-clusters:
    - capi

  - name: nginx-ingress
    url: https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-3.34.0/ingress-nginx-3.34.0.tgz
    type: helm
    chartoverride: file://{{ .Workspace }}/config/service-overrides/ingress/generic-nginx-ingress.yml
    images:
      - k8s.gcr.io/ingress-nginx/controller:v0.47.0
      - docker.io/jettech/kube-webhook-certgen:v1.5.1
      - k8s.gcr.io/defaultbackend-amd64:1.5
    wait:
      timeout: 300
    supported-clusters:
    - capi

  - name: prometheus
    namespace: prometheus
    url: https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-33.2.1/kube-prometheus-stack-33.2.1.tgz
    chartoverride: file://{{ .Workspace }}/config/service-overrides/prometheus/prometheus-override.yml
    type: helm
    images:
      - quay.io/prometheus-operator/prometheus-config-reloader:v0.54.1
      - quay.io/prometheus/alertmanager:v0.23.0
      - quay.io/kiwigrid/k8s-sidecar:1.15.6
      - grafana/grafana:8.3.6
      - quay.io/prometheus-operator/prometheus-operator:v0.54.1
      - quay.io/prometheus/prometheus:v2.33.4
      - k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
      - quay.io/thanos/thanos:v0.24.0
    supported-clusters:
    - kind
    - rke
    - capi
    wait:
      timeout: 300

  - name: multus
    url: file://{{ .Workspace }}/services/multus/multus-daemonset.yml
    type: yaml
    images:
      - ghcr.io/k8snetworkplumbingwg/multus-cni:stable
    supported-clusters:
    - kind
    - rke
    - capi

  - name: rook-ceph
    namespace: rook-ceph
    url: https://charts.rook.io/release/rook-ceph-v1.8.8.tgz
    type: helm
    chartoverride: file://{{ .Workspace }}/config/service-overrides/rook-ceph/rook-ceph-override.yml
    supported-clusters:
    - rke
    - capi
    wait:
      timeout: 300

  - name: rook-ceph-cluster
    namespace: rook-ceph
    url: https://charts.rook.io/release/rook-ceph-cluster-v1.8.8.tgz
    type: helm
    chartoverride: file://{{ .Workspace }}/config/service-overrides/rook-ceph/rook-ceph-cluster-override.yml
    supported-clusters:
    - rke
    - capi
    wait:
      timeout: 300

  - name: kubevirt-operator
    url: https://github.com/kubevirt/kubevirt/releases/download/v0.50.0/kubevirt-operator.yaml
    type: yaml
    supported-clusters:
    - kind
    - rke
    - capi

  - name: kubevirt-cr
    url: https://github.com/kubevirt/kubevirt/releases/download/v0.50.0/kubevirt-cr.yaml
    type: yaml
    supported-clusters:
    - kind
    - rke
    - capi

  - name: akri
    namespace: akri-component
    url: https://project-akri.github.io/akri/akri-0.8.4.tgz
    chartoverride: file://{{ .Workspace }}/config/service-overrides/akri/akri-override.yml
    hash: 11922f4760eef7c2fd93a552fd87128dcb1e2995927f0e4e6eccfd579e26631c
    hashtype: sha256
    chartname: akri
    type: helm
    images:
      - ghcr.io/project-akri/akri/controller:v0.8.4
      - ghcr.io/project-akri/akri/agent:v0.8.4
      - ghcr.io/project-akri/akri/udev-discovery:v0.8.4
      - ghcr.io/project-akri/akri/udev-video-broker:v0.8.4
      - ghcr.io/project-akri/akri/onvif-discovery:v0.8.4
      - ghcr.io/project-akri/akri/onvif-video-broker:v0.8.4
    supported-clusters:
    - rke
    - capi

  - name: portainer-ce
    url: https://github.com/portainer/k8s/releases/download/portainer-1.0.22/portainer-1.0.22.tgz
    hash: eebb6baefd2a74c13acb6ae143ad6ee874b47f282db82bf5274462bee042d47c
    hashtype: sha256
    chartoverride: file://{{ .Workspace }}/config/service-overrides/portainer-ce/portainer-override.yml
    type: helm
    images:
    - busybox:latest
    - portainer/portainer-ce:2.11.1
    supported-clusters:
    - kind
    - rke
    - capi

  - name: nfd
    namespace: node-feature-discovery
    helmrepo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    chartname: node-feature-discovery
    chartversion: v0.11.0
    chartoverride: file://{{ .Workspace }}/config/service-overrides/nfd/nfd-override.yml
    type: helm
    images:
    - k8s.gcr.io/nfd/node-feature-discovery:v0.11.0
    supported-clusters:
    - rke
    - capi

  - name: intel-gpu-plugin
    namespace: kube-system
    url: file://{{ .Workspace }}/config/gpu/intel-gpu-plugin.yml
    type: yaml
    images:
    - intel/intel-gpu-initcontainer:0.23.0
    - intel/intel-gpu-plugin:0.23.0
    supported-clusters:
    - rke
    - capi

  - name: intel-sriov-network
    url: file://{{ .Workspace }}/config/sriov/setup_sriov_network.yml
    type: yaml
    images:
    - ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.4.0
    - ghcr.io/k8snetworkplumbingwg/sriov-cni
    supported-clusters:
    - rke
    - capi

  - name: rt-linux-detection
    type: dce
    executor:
      build: config/executor/rt-linux-detection/build-rt-linux-detection.yml
      deploy: config/executor/rt-linux-detection/deploy-rt-linux-detection.yml
    resources:
      - name: "helm"
        value: https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
    supported-clusters:
    - kind
    - rke
    - capi


    
